---
abstract: 'Library for creating easy mail filters'
author:
  - 'Simon Cozens <simon@cpan.org> wrote versions 1 and 2.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Mail::Audit
name: Mail-Audit
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Fcntl: 0
  File::HomeDir: 0.61
  File::Temp: 0
  File::Tempdir: 0
  MIME::Entity: 0
  Mail::Internet: 0
  Mail::Mailer: 0
  Net::SMTP: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 2.225
