author: 'Ricardo SIGNES <rjbs@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Mail-Audit
no_index:
  directory:
    - inc
    - t
requires:
  Fcntl: 0
  MIME::Entity: 0
  Mail::Internet: 0
  Mail::ListDetector: 0
  Mail::Mailer: 0
  Net::SMTP: 0
version: 2.200_04
