---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Audit
no_index:
  directory:
    - t
    - inc
requires:
  Fcntl: 0
  File::HomeDir: 0.61
  File::Temp: 0
  File::Tempdir: 0
  MIME::Entity: 0
  Mail::Internet: 0
  Mail::Mailer: 0
  Net::SMTP: 0
resources:
  x_Repository: http://github.com/rjbs/mail-audit
version: 2.227
